### ISSUE TITLE
[feat] 개발 환경 세팅

### ISSUE THREAD

**Issue by im-madylin** [im-madylin/im-madylin.github.io#1]
## 💎 Requirements

포트폴리오 웹사이트 구현을 위한 개발 환경 세팅

## ✨ Todo

- [x] next.js Typescript 프로젝트 생성
- [x] Tailwind CSS 설치
- [x] ES Lint 설치
- [x] Prettier 설치
- [x] Prettier plugin tailwindcss 설치
- [x] Husky + Lint-staged 설치
- [x] Github Pages 배포 설정
