### ISSUE TITLE
[feat] 포트폴리오 표지 화면 구현

### ISSUE THREAD

**Issue by im-madylin** [im-madylin/im-madylin.github.io#3]
## 💎 Requirements

포트폴리오 웹사이트의 표지 화면 구현

## ✨ Todo

- [x] 타이틀 추가
- [x] 이미지 추가
- [x] Last update 정보 추가
- [x] 스크롤 지시 아이콘 추가
- [x] 네비게이션바, 위로가기 버튼 추가

## 🐣 ETC

애니메이션, 기능은 추후 적용
