### ISSUE TITLE
[feat] 포트폴리오 Projects 화면 구현

### ISSUE THREAD

**Issue by im-madylin** [im-madylin/im-madylin.github.io#7]
## 💎 Requirements

포트폴리오 웹사이트의 Projects 화면 구현

## ✨ Todo

- [x] 타이틀 추가
- [x] 기간 및 참여인원 정보 추가
- [x] 프로젝트 이미지 추가
- [x] 프로젝트 설명 추가
- [x] 프로젝트 기술 추가
- [x] 더 알아보기 버튼 추가

## 🐣 ETC

애니메이션, 기능은 추후 적용
